import nodemailer from 'nodemailer';

export const transporter = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "1d1e15541690ed", // generated by Mailtrap
      pass: "88582e03c3bb5a" // generated by Mailtrap
    }
  });
